# Generated by Django 5.0.6 on 2024-10-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_approved',
            new_name='book',
        ),
    ]
