# Generated by Django 5.0.6 on 2024-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_is_approved_booking_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book',
            new_name='is_booked',
        ),
        migrations.RemoveField(
            model_name='property',
            name='seller',
        ),
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
